{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-timechange
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/timechange_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/timechange/timechange_{{ version }}.tar.gz
  sha256: 6dc8ff9d339d3c4cff7ddf3800383f3e94f41c021f6c7bacccf971e187f73feb

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-cpp11 >=0.2.7

  run:
    - r-base
    - r-cpp11 >=0.2.7

test:
  commands:
    - $R -e "library('timechange')"  # [not win]
    - "\"%R%\" -e \"library('timechange')\""  # [win]

about:
  home: https://github.com/vspinu/timechange/
  license: GPL-3.0-only AND Apache-2.0
  summary: Efficient routines for manipulation of date-time objects while accounting for time-zones and daylight saving times. The package includes utilities for updating of date-time components (year, month, day etc.), modification of time-zones, rounding of date-times, period addition and subtraction etc. Parts of 
    the 'CCTZ' source code, released under the Apache 2.0 License, are included in this package. See <https://github.com/google/cctz> for more details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - cctz_LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan
